### ISSUE TITLE
后端接口全部返回403错误

### ISSUE THREAD

**Issue by cai1818** [caojen/pgms-backend#1]
![4e66b774e65746af570de61b931549b](https://user-images.githubusercontent.com/72693103/195011075-d8997a0b-44da-4509-8a22-91a3745aa54e.png)

**Comment by caojen** [comment]
@cai1818  我需要看一下403请求的详细内容。

> 浏览器控制台 -> Network -> 点击Status=403的请求 -> Response

**Comment by caojen** [comment]
有一些数据初始化的指南在旧版本的README里面没有提及到，现在已经更新。

https://github.com/caojen/pgms-backend/blob/master/README.md

**Comment by cai1818** [comment]
感谢回复，如果我们之后再遇到问题会再询问的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月11日(周二) 下午2:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [caojen/pgms-backend] 后端接口全部返回403错误 (Issue #1)




 
有一些数据初始化的指南在旧版本的README里面没有提及到，现在已经更新。
 
https://github.com/caojen/pgms-backend/blob/master/README.md

**Comment by cai1818** [comment]
师兄您好，我们重新按照readme搭建服务器，发现seaweedfs会报错，所以之后的数据初始化也会报错，并没有更改过dockercompose



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月11日(周二) 下午2:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [caojen/pgms-backend] 后端接口全部返回403错误 (Issue #1)




 
有一些数据初始化的指南在旧版本的README里面没有提及到，现在已经更新。
 
https://github.com/caojen/pgms-backend/blob/master/README.md

**Comment by caojen** [comment]
> 师兄您好，我们重新按照readme搭建服务器，发现seaweedfs会报错，所以之后的数据初始化也会报错，并没有更改过dockercompose

报的什么错，看看日志

**Comment by cai1818** [comment]
额，就是刚刚那一个邮件的附件图片，输入那些指令，会报各种error



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月13日(周四) 晚上8:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [caojen/pgms-backend] 后端接口全部返回403错误 (Issue #1)




  
师兄您好，我们重新按照readme搭建服务器，发现seaweedfs会报错，所以之后的数据初始化也会报错，并没有更改过dockercompose
  
报的什么错，看看日志

**Comment by caojen** [comment]
ok，我找找图片。用github issue吧。邮件不方便。

**Comment by caojen** [comment]
用github issue重新发一次吧，看起来你发的附件被吞掉了，发给我的邮件里面没有附件。

**Comment by cai1818** [comment]
![DGI02}S@NR~0`I0842$NX1H](https://user-images.githubusercontent.com/72693103/195600551-6df2a5f0-ecae-40a8-89c5-a8bf28d976d2.png)


![G3C_YVF$8 Z`{KOITU_FENN](https://user-images.githubusercontent.com/72693103/195600576-4187ffcb-9b74-4b62-a6c7-673f6b2a79d5.png)

**Comment by caojen** [comment]
本地的docker-compose版本是？

**Comment by cai1818** [comment]
docker-compose version 1.25.0, build unknown

**Comment by caojen** [comment]
https://github.com/docker/compose/issues/6998#issuecomment-567504403

看起来是docker-compose v1.25.0的已知错误。

我本地使用的docker-compose版本号是1.29.2, build 5becea4c。解析yml文件时没有问题。供你参考。

**Comment by cai1818** [comment]
![4c4771a06d4734a0f41e700f7476051](https://user-images.githubusercontent.com/72693103/195619119-89baef5a-fb20-49c0-84f8-08452c49aca4.png)
请问这个http://127.19.0.3:8080怎么更改，因为本机8080端口有别的用处，所以要改一下

**Comment by cai1818** [comment]
请问127.19.0.3是哪里的主机ip呢

**Comment by caojen** [comment]
更改端口的方法：

进入docker-compose.yml，将里面的8080统一改成其他端口就好了。

`127.19.0.3:8080`这个其实是在上一步`curl http://xxx:xxxx/dir/assign`中返回的PublicUrl

**Comment by cai1818** [comment]
![Uploading f80858160b0a1e8c5f414e95e80a208.png…]()
😵

**Comment by cai1818** [comment]
![f80858160b0a1e8c5f414e95e80a208](https://user-images.githubusercontent.com/72693103/195748406-1f84633c-3565-49dc-b3e8-cad9910bf1d2.png)

**Comment by caojen** [comment]
输入的命令是不是有问题。截图不全，做不了下一步的判断。

**Comment by cai1818** [comment]
额，就是按照readme的顺序输入命令，然后更改了dockercompose的端口为18181

**Comment by caojen** [comment]
```
curl -F file=@static/defualt_image.jpeg 'http://127.21.0.3:18181'
```
试试这样？

**Comment by cai1818** [comment]
![dd00c251b957d8d656dc0f50935c9e3](https://user-images.githubusercontent.com/72693103/195751475-288d5732-2f60-4028-a3e8-ac4ba2f81879.png)
会直接Fail to open

**Comment by caojen** [comment]
你的shell是windows上的wsl吗？

看看这个文件是否存在：
```
ls -l static/default_image.jpeg
```

**Comment by cai1818** [comment]
![39f12b0753c10f487f7176212baec2d](https://user-images.githubusercontent.com/72693103/195751965-61bc49d3-94e9-4eb2-8c27-b8bba83d53ee.png)
default写错了，改了下，还是error

**Comment by caojen** [comment]
ok, 我研究一下

**Comment by cai1818** [comment]
![45bd328653ff2ce0be8ce537fee28db](https://user-images.githubusercontent.com/72693103/195752061-a3afd2ff-dab9-45ba-a1ca-d2855764ca76.png)
cun'zai存在

**Comment by cai1818** [comment]
shell是Linux
![50ee18bdea825bd054f96445057f08f](https://user-images.githubusercontent.com/72693103/195752314-596577f4-1842-4889-bb3a-53431482f590.png)

**Comment by caojen** [comment]
将你修改后的docker-compose.yml文件（改了端口之后的）发一下。用markdown语法吧，避免截图。
![image](https://user-images.githubusercontent.com/43436876/195752853-6ac28eef-6f33-49cc-bd99-c5fcc688bb3b.png)

将文件内容粘贴到代码块里面。

**Comment by cai1818** [comment]
```
version: '2'

services:
  master:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master"
  volume:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 18181:18181
      - 18080:18080
      - 9325:9325
    command: 'volume -mserver="master:9333" -port=18181  -metricsPort=9325'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: 'filer -master="master:9333"  -metricsPort=9326'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8333:8333
      - 9327:9327
    command: 's3 -filer="filer:8888" -metricsPort=9327'
    depends_on:
      - master
      - volume
      - filer
  webdav:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 7333:7333
    command: 'webdav -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer
  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - s3
```
